include: package:flutter_lints/flutter.yaml
linter:
  rules:
    await_only_futures: true
    always_declare_return_types: true
    prefer_single_quotes: true
    unawaited_futures: true
    unsafe_html: true
    omit_local_variable_types: true